### ISSUE TITLE
Support FreeBSD

### ISSUE THREAD

**Issue by rzr** [rzr/pinball-table-hurd#11]
I know there is a bug in loader for gnu table (fix in in master branch )

May it worth to be compared for the hurd one

Relate-to: https://gist.github.com/thierry-FreeBSD/d87720858a646c557e5cd7b196bcd3b1#gistcomment-3570129

cc: @thierry-FreeBSD

**Comment by thierry-FreeBSD** [comment]
Here is a backtrace:
```
#0  Loader::loadModule (this=0x801127220, file=..., ist=..., group=0x804d73d00) at Loader.cpp:704
#1  0x000000000026ba2f in Loader::loadMisc (this=0x801127220, file=..., ist=..., engine=0x8010c6000, group=0x804d73d00, beh=0x0) at Loader.cpp:764
#2  0x000000000026fa52 in Loader::loadStdObject (this=0x801127220, file=..., ist=..., engine=0x8010c6000) at Loader.cpp:814
#3  0x000000000027252b in Loader::loadFile (this=0x801127220, fn=0x804c683e0 "/usr/local/share/pinball/hurd/pinball.pbl", engine=0x8010c6000) at Loader.cpp:1014
#4  0x000000000028f8e0 in Table::loadLevel (this=0x802a38ce0, engine=0x8010c6000, subdir=0x8010ffd74 "hurd") at Table.cpp:141
#5  0x0000000000264f38 in MyMenuLoad::perform (this=0x8010ffd50) at Pinball.cpp:383
#6  0x00000000002999fa in MenuSub::perform (this=0x8010b6880) at Menu.cpp:79
#7  0x00000000002999fa in MenuSub::perform (this=0x8010b6dc0) at Menu.cpp:79
#8  0x0000000000263449 in Pinball::loop (this=0x7fffffffe010) at Pinball.cpp:857
#9  0x0000000000262d23 in Pinball::run (this=0x7fffffffe010, argc=1, argv=0x7fffffffe0c0) at Pinball.cpp:748
#10 0x0000000000263643 in Pinball::main (argc=1, argv=0x7fffffffe0c0) at Pinball.cpp:901
#11 0x00000000002636d9 in main (argc=1, argv=0x7fffffffe0c0) at Pinball.cpp:989

```

**Comment by rzr** [comment]
Are you able to replicate this issue @lanodan ?

Relate-to: https://github.com/adoptware/pinball/issues/17

**Comment by rzr** [comment]
While building snap package of pinball I saw this warning and thought about this issue:

    libtool: warning: remember to run 'libtool --finish /usr/local/lib/pinball'

Does this help ?

**Comment by thierry-FreeBSD** [comment]
Thanks, but we always do that, and unfortunately it does not help in this case.

**Comment by rzr** [comment]
It's still not listed at:

https://repology.org/project/pinball-table-hurd/versions#

Any clue what is blocking packaging here ?

**Comment by thierry-FreeBSD** [comment]
You can find the FreeBSD port of pinball here: https://repology.org/project/pinball/versions
But we do not have a separate package for pinball-table-hurd.
